"""Text summarization agent built on the Gogi platform.

The agent lets a user upload documents and then ask for summaries of them. It brings together
the following Gogi services:

- Indexes:   every user gets an index in which their uploaded documents live
- Prompts:   the system prompt and summary prompt template are kept in the prompt registry
- Workflows: uploaded documents are embedded (with OpenAI) by an asynchronous ingestion workflow
- Documents: the RAG pipeline retrieves the chunks relevant to the user query from the index
- Models:    the summary is generated by an OpenAI chat model through the Gogi LLM gateway

Run it with, e.g.

    python examples/agents/summarization/agent.py --file my_report.pdf \
        --query "Summarize the main findings of the report"

Without --file, a small sample document is uploaded instead.
"""

import argparse
import json
import os
import tempfile
import uuid
from pathlib import Path

from ingestion_workflow import (
    EMBEDDINGS_CLIENT,
    EMBEDDINGS_MODEL,
    ingest_document_workflow,
    register_ingestion_workflow,
    submit_ingestion_job,
    wait_for_workflow_job,
)
from loguru import logger
from prompts import load_prompts, register_prompts
from rag_pipeline import RAGPipeline, RAGResult
from rich import print as rich_print

from gogi.gogi import Gogi
from gogi.models import LLMRunRequestConfig

GOGI_GATEWAY_URL = os.getenv("GOGI_GATEWAY_URL", "localhost:50051")
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-4o-mini")


class SummarizationAgent:
    def __init__(self, platform: Gogi, owner: str, run_workflows_locally: bool = True):
        """
        Args:
            platform: Connection to the Gogi platform.
            owner: The user the agent works for. Their documents are stored in their own index.
            run_workflows_locally: When True, the ingestion workflow is executed in this process for every
                job the agent creates. Set it to False once the workflow is deployed on the platform, in which
                case the platform runtime picks up the jobs and the agent only waits for them to finish.
        """
        self.platform = platform
        self.owner = owner
        self.index_name = f"{owner}-summarization"
        self.run_workflows_locally = run_workflows_locally

        self._workflow_id: str | None = None
        self._pipeline: RAGPipeline | None = None

    def setup(self) -> None:
        """Create the user's index, register the prompts and the ingestion workflow."""
        existing = {index.index_name for index in self.platform.indexes.list_owner_indexes(owner_name=self.owner)}
        if self.index_name not in existing:
            self.platform.indexes.create_index(index_name=self.index_name, owner_name=self.owner)
            logger.info(f"Created index {self.index_name}")

        prompt_ids = register_prompts(
            self.platform, index_name=self.index_name, author=self.owner, model=OPENAI_CHAT_MODEL
        )
        self._workflow_id = register_ingestion_workflow(self.platform)

        self._pipeline = RAGPipeline(
            platform=self.platform,
            index_name=self.index_name,
            prompts=load_prompts(self.platform, prompt_ids),
            llm_config=LLMRunRequestConfig(
                model=OPENAI_CHAT_MODEL, provider="openai", temperature=0.1, max_tokens=1000
            ),
            embeddings_client=EMBEDDINGS_CLIENT,
            embeddings_model=EMBEDDINGS_MODEL,
        )

    def upload(self, path: Path) -> str:
        """Upload a document and wait until it has been embedded. Returns the document id."""
        if self._workflow_id is None:
            raise RuntimeError("Call setup() before uploading documents")

        document_id = uuid.uuid4().hex
        job_id, job_input = submit_ingestion_job(
            self.platform,
            workflow_id=self._workflow_id,
            index_name=self.index_name,
            document_id=document_id,
            filename=path.name,
            content=path.read_bytes(),
        )
        logger.info(f"Submitted ingestion job {job_id} for {path.name}")

        if self.run_workflows_locally:
            ingest_document_workflow(job_id=job_id, **job_input)

        job = wait_for_workflow_job(self.platform, job_id=job_id)
        logger.info(f"Ingestion finished: {json.loads(job.result_json)}")

        return document_id

    def summarize(self, query: str, document_id: str | None = None) -> RAGResult:
        """Summarize the user's documents according to the query.
        If document_id is given, only that document is used; otherwise the whole index is searched.
        """
        if self._pipeline is None:
            raise RuntimeError("Call setup() before asking for summaries")

        document_ids = [document_id] if document_id else None
        return self._pipeline.run(query=query, document_ids=document_ids)


def create_sample_document() -> Path:
    content = """
    GloboTech Employee Handbook (2026 edition)

    Section 1: Paid Time Off
    All full-time employees receive exactly 27 days of paid vacation per year.
    Unused vacation days roll over, but the maximum carryover is 8 days.
    Employees in the Zurich office receive an additional 3 floating holidays.

    Section 2: Remote Work
    Employees may work remotely up to 3 days per week. Wednesday is a mandatory in-office day for all
    teams. Remote work from outside the employee's home country requires written approval from the VP of
    People Operations at least 14 business days in advance.

    Section 3: Expense Policy
    The daily meal allowance during business travel is $67 USD. Flights over 6 hours qualify for business
    class. Employees must submit expense reports within 11 calendar days of trip completion.

    Section 4: Annual Bonus
    The annual bonus target is 14% of base salary for individual contributors and 19% for managers.
    Bonuses are paid in the March payroll cycle.
    """
    path = Path(tempfile.mkdtemp()) / "employee_handbook.txt"
    path.write_text(content.strip())
    return path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Gogi text summarization agent")
    parser.add_argument("--file", type=Path, help="Document to summarize. A sample document is used if omitted")
    parser.add_argument("--query", default="Summarize the document", help="What to summarize")
    parser.add_argument("--owner", default="summarization-demo-user", help="The user that owns the documents")
    parser.add_argument(
        "--deployed", action="store_true", help="The ingestion workflow is deployed; don't run it in this process"
    )
    args = parser.parse_args()

    platform = Gogi(gateway_url=GOGI_GATEWAY_URL, logger=logger)

    agent = SummarizationAgent(platform=platform, owner=args.owner, run_workflows_locally=not args.deployed)
    agent.setup()

    document_id = agent.upload(args.file or create_sample_document())

    result = agent.summarize(query=args.query, document_id=document_id)
    rich_print(f"[bold]Summary[/bold]\n{result.summary}\n")
    rich_print(f"[dim]Grounded on {len(result.chunks)} chunks; token usage: {result.token_usage}[/dim]")
